export const PLAY_TURNTABLE = "PLAY_TURNTABLE";
export const REMOVE_TURNTABLE = "REMOVE_TURNTABLE";
export const REGISTER_TURNTABLE = "REGISTER_TURNTABLE";
export const SET_TURNTABLE_PITCH = "SET_TURNTABLE_PITCH";